# Generated by Django 4.1.2 on 2023-03-30 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='ur1',
            new_name='url',
        ),
    ]
